### ISSUE TITLE
Images are too heavy causing lots of empty white space before image loading which isn't ideal

### ISSUE THREAD

**Issue by VahuBali** [ACuteWoof/acutewoof.github.io#2]
An example of this is

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/67645126/140583724-5d166182-2b81-4842-afab-07f93f744426.png">

**Comment by ACuteWoof** [comment]
Hmm, the images are already 768p, and I don't think it'll look good if I compress it. 🤔
